// Column metadata transcribed from the authoritative SQL DDL, not INSERT examples.
import type { TableName } from "@/types/db";
export interface ColumnDefinition {
  kind: "string" | "number" | "boolean" | "json";
  nullable: boolean;
  default?: string | number | boolean;
  maxLength?: number;
  integer?: boolean;
  unsigned?: boolean;
  date?: string;
  values?: string[];
  references?: TableName;
}
export const tableDefinitions: Record<TableName, Record<string, ColumnDefinition>> = {
  user: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    first_name: { kind: "string", nullable: false, maxLength: 80 },
    middle_name: { kind: "string", nullable: true, maxLength: 80 },
    last_name: { kind: "string", nullable: false, maxLength: 80 },
    username: { kind: "string", nullable: false, maxLength: 60 },
    password_hash: { kind: "string", nullable: false, maxLength: 255 },
    phone_number: { kind: "string", nullable: true, maxLength: 12 },
    email: { kind: "string", nullable: true, maxLength: 160 },
  },
  pillar: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    code: { kind: "string", nullable: false, maxLength: 20 },
    name: { kind: "string", nullable: false, maxLength: 120 },
    focus_description: { kind: "string", nullable: true },
    lead_user_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "user",
    },
  },
  county: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    name: { kind: "string", nullable: false, maxLength: 60 },
  },
  sub_county: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    county_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "county",
    },
    name: { kind: "string", nullable: false, maxLength: 80 },
  },
  ward: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    sub_county_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "sub_county",
    },
    name: { kind: "string", nullable: false, maxLength: 80 },
  },
  donor: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    name: { kind: "string", nullable: false, maxLength: 160 },
    notes: { kind: "string", nullable: true },
  },
  business_sector: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    name: { kind: "string", nullable: false, maxLength: 80 },
  },
  case_type: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    pillar_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "pillar",
    },
    name: { kind: "string", nullable: false, maxLength: 120 },
    requires_p3_prc_forms: { kind: "boolean", nullable: false, default: false },
    default_route: { kind: "string", nullable: false, maxLength: 30 },
  },
  partner_institution: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    name: { kind: "string", nullable: false, maxLength: 160 },
    institution_type: { kind: "string", nullable: false, maxLength: 30 },
    county_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "county",
    },
    contact_details: { kind: "string", nullable: true, maxLength: 255 },
  },
  activity_type_definition: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    pillar_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "pillar",
    },
    name: { kind: "string", nullable: false, maxLength: 120 },
    description: { kind: "string", nullable: true },
  },
  activity_topic: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    activity_type_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "activity_type_definition",
    },
    name: { kind: "string", nullable: false, maxLength: 160 },
    description: { kind: "string", nullable: true },
    sequence_no: { kind: "number", nullable: false, integer: true, unsigned: true },
  },
  role: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    code: { kind: "string", nullable: false, maxLength: 40 },
    name: { kind: "string", nullable: false, maxLength: 120 },
    description: { kind: "string", nullable: true },
    is_system_role: { kind: "boolean", nullable: false, default: false },
  },
  user_role: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    user_id: { kind: "number", nullable: false, integer: true, unsigned: true, references: "user" },
    role_id: { kind: "number", nullable: false, integer: true, unsigned: true, references: "role" },
    pillar_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "pillar",
    },
  },
  permission: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    code: { kind: "string", nullable: false, maxLength: 60 },
    module: { kind: "string", nullable: false, maxLength: 40 },
    name: { kind: "string", nullable: false, maxLength: 160 },
    description: { kind: "string", nullable: true },
  },
  role_permission: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    role_id: { kind: "number", nullable: false, integer: true, unsigned: true, references: "role" },
    permission_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "permission",
    },
  },
  participant: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    sync_ref: { kind: "string", nullable: true, maxLength: 80 },
    first_name: { kind: "string", nullable: false, maxLength: 80 },
    middle_name: { kind: "string", nullable: true, maxLength: 80 },
    last_name: { kind: "string", nullable: false, maxLength: 80 },
    id_number: { kind: "string", nullable: true, maxLength: 40 },
    id_number_type: { kind: "string", nullable: true, maxLength: 30 },
    date_of_birth: { kind: "string", nullable: true, date: "date" },
    gender: { kind: "string", nullable: true, maxLength: 20 },
    phone_number: { kind: "string", nullable: true, maxLength: 30 },
    ward_id: { kind: "number", nullable: true, integer: true, unsigned: true, references: "ward" },
    is_person_with_disability: { kind: "boolean", nullable: false, default: false },
    is_refugee: { kind: "boolean", nullable: false, default: false },
    is_consent_given: { kind: "boolean", nullable: false, default: false },
    remarks: { kind: "string", nullable: true },
  },
  organisation: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    name: { kind: "string", nullable: false, maxLength: 200 },
    legal_form: { kind: "string", nullable: false, maxLength: 30 },
    registration_number: { kind: "string", nullable: true, maxLength: 80 },
    ward_id: { kind: "number", nullable: true, integer: true, unsigned: true, references: "ward" },
    address: { kind: "string", nullable: true, maxLength: 255 },
    board_size: { kind: "number", nullable: true, integer: true, unsigned: true },
    board_women_count: { kind: "number", nullable: true, integer: true, unsigned: true },
    board_youth_count: { kind: "number", nullable: true, integer: true, unsigned: true },
    has_bank_account: { kind: "boolean", nullable: true },
    financial_mgmt_notes: { kind: "string", nullable: true },
    safeguarding_policies: { kind: "json", nullable: true },
    due_diligence_status: {
      kind: "string",
      nullable: false,
      default: "not_started",
      maxLength: 20,
    },
    due_diligence_date: { kind: "string", nullable: true, date: "date" },
  },
  external_provider: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    first_name: { kind: "string", nullable: false, maxLength: 80 },
    middle_name: { kind: "string", nullable: true, maxLength: 80 },
    last_name: { kind: "string", nullable: false, maxLength: 80 },
    provider_type: { kind: "string", nullable: false, maxLength: 40 },
    service_description: { kind: "string", nullable: true, maxLength: 255 },
    affiliated_institution_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "partner_institution",
    },
    phone_number: { kind: "string", nullable: true, maxLength: 30 },
    email: { kind: "string", nullable: true, maxLength: 160 },
    notes: { kind: "string", nullable: true },
  },
  enrollment: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    participant_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "participant",
    },
    organisation_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "organisation",
    },
    pillar_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "pillar",
    },
    entry_category: { kind: "string", nullable: false, maxLength: 120 },
  },
  document: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    owner_type: { kind: "string", nullable: false, maxLength: 40 },
    owner_id: { kind: "number", nullable: false, integer: true, unsigned: true },
    document_type: { kind: "string", nullable: false, maxLength: 60 },
    file_url: { kind: "string", nullable: false, maxLength: 500 },
  },
  assessment_instrument: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    code: { kind: "string", nullable: false, maxLength: 30 },
    name: { kind: "string", nullable: false, maxLength: 160 },
    notes: { kind: "string", nullable: false, maxLength: 160 },
    scoring_scale: { kind: "string", nullable: true, maxLength: 20 },
  },
  assessment_criterion: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    instrument_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "assessment_instrument",
    },
    section: { kind: "string", nullable: false, maxLength: 120 },
    label: { kind: "string", nullable: false, maxLength: 200 },
    max_score: { kind: "number", nullable: true, integer: true, unsigned: true },
    sort_order: { kind: "number", nullable: false, default: 0, integer: true },
  },
  organisation_assessment: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    organisation_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "organisation",
    },
    instrument_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "assessment_instrument",
    },
    donor_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "donor",
    },
    respondent_names: { kind: "json", nullable: true },
    section_comments: { kind: "json", nullable: true },
    overall_recommendation: { kind: "string", nullable: true, maxLength: 60 },
    recorded_by: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "user",
    },
  },
  organisation_assessment_score: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    assessment_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "organisation_assessment",
    },
    criterion_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "assessment_criterion",
    },
    score: { kind: "number", nullable: true, integer: true },
    notes: { kind: "string", nullable: true },
  },
  assessment_document_check: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    assessment_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "organisation_assessment",
    },
    document_name: { kind: "string", nullable: false, maxLength: 160 },
    document_check_status: {
      kind: "string",
      nullable: false,
      default: "not_obtained",
      maxLength: 20,
    },
    document_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "document",
    },
    notes: { kind: "string", nullable: true },
  },
  pipeline_definition: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    pillar_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "pillar",
    },
    name: { kind: "string", nullable: false, maxLength: 160 },
    version: { kind: "number", nullable: false, default: 1, integer: true },
  },
  stage_definition: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    pipeline_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "pipeline_definition",
    },
    step_no: { kind: "number", nullable: false, integer: true },
    name: { kind: "string", nullable: false, maxLength: 160 },
    description: { kind: "string", nullable: true },
    trigger_description: { kind: "string", nullable: true },
    key_activities: { kind: "string", nullable: true },
    documents_needed: { kind: "string", nullable: true },
    system_tool: { kind: "string", nullable: true, maxLength: 120 },
    typical_duration: { kind: "string", nullable: true, maxLength: 80 },
    completion_criteria: { kind: "string", nullable: true },
    leads_to_pillar_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "pillar",
    },
  },
  participant_stage_event: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    enrollment_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "enrollment",
    },
    stage_definition_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "stage_definition",
    },
    local_ref: { kind: "string", nullable: true, maxLength: 80 },
    event_date: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    stage_event_status: { kind: "string", nullable: false, default: "recorded", maxLength: 20 },
    source_channel: { kind: "string", nullable: false, default: "mobile", maxLength: 20 },
    notes: { kind: "string", nullable: true },
  },
  project: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    pillar_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "pillar",
    },
    name: { kind: "string", nullable: false, maxLength: 200 },
    notes: { kind: "string", nullable: true },
    donor_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "donor",
    },
    start_date: { kind: "string", nullable: true, date: "date" },
    end_date: { kind: "string", nullable: true, date: "date" },
  },
  referral: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    enrollment_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "enrollment",
    },
    from_pillar_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "pillar",
    },
    to_pillar_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "pillar",
    },
    from_stage_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "stage_definition",
    },
    to_project_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "project",
    },
    to_partner_institution_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "partner_institution",
    },
    trigger_reason: { kind: "string", nullable: true },
    notes: { kind: "string", nullable: true },
    // Proposed addition: the trainee record whose grant recommendation created this referral.
    source_training_enrollment_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "training_enrollment",
    },
  },
  legal_case: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    enrollment_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "enrollment",
    },
    case_type_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "case_type",
    },
    court_name: { kind: "string", nullable: true, maxLength: 160 },
    assigned_officer: { kind: "string", nullable: true, maxLength: 160 },
    next_court_date: { kind: "string", nullable: true, date: "date" },
    court_file_number: { kind: "string", nullable: true, maxLength: 80 },
    ob_number: { kind: "string", nullable: true, maxLength: 80 },
    counsellor: { kind: "string", nullable: true, maxLength: 160 },
    mediation_attempted: { kind: "boolean", nullable: false, default: false },
    mediation_outcome: { kind: "string", nullable: true, maxLength: 20 },
    court_status: { kind: "string", nullable: true, maxLength: 20 },
    ruling_date: { kind: "string", nullable: true, date: "date" },
    outcome_notes: { kind: "string", nullable: true },
    advocate_provider_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "external_provider",
    },
    opened_date: { kind: "string", nullable: false, date: "date" },
    closed_date: { kind: "string", nullable: true, date: "date" },
  },
  counselling_session: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    enrollment_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "enrollment",
    },
    session_no: { kind: "number", nullable: false, integer: true },
    session_date: { kind: "string", nullable: false, date: "date" },
    session_type: { kind: "string", nullable: false, maxLength: 30 },
    counsellor_provider_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "external_provider",
    },
    notes: { kind: "string", nullable: true },
  },
  training_enrollment: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    enrollment_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "enrollment",
    },
    pathway: {
      kind: "string",
      nullable: false,
      maxLength: 30,
      values: ["tvet", "apprenticeship", "community_center", "life_skills"],
    },
    partner_institution_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "partner_institution",
    },
    trainer_provider_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "external_provider",
    },
    course_name: { kind: "string", nullable: true, maxLength: 160 },
    start_date: { kind: "string", nullable: true, date: "date" },
    completion_date: { kind: "string", nullable: true, date: "date" },
    training_status: {
      kind: "string",
      nullable: false,
      default: "ongoing",
      maxLength: 20,
      values: ["ongoing", "dropped_out", "completed"],
    },
    current_work_status: {
      kind: "string",
      nullable: true,
      maxLength: 120,
      values: ["employed", "self_employed", "further_training", "seeking_work", "not_seeking_work"],
    },
    workstation: { kind: "string", nullable: true, maxLength: 160 },
    monthly_salary: { kind: "number", nullable: true },
    recommended_for_grant: { kind: "boolean", nullable: false, default: false },
  },
  activity_session: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    pillar_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "pillar",
    },
    enrollment_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "enrollment",
    },
    activity_type_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "activity_type_definition",
    },
    activity_topic_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "activity_topic",
    },
    session_date: { kind: "string", nullable: false, date: "date" },
    venue: { kind: "string", nullable: true, maxLength: 160 },
    topic: { kind: "string", nullable: true, maxLength: 200 },
    facilitator_user_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "user",
    },
    facilitator_provider_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "external_provider",
    },
    notes: { kind: "string", nullable: true },
  },
  activity_attendance: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    session_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "activity_session",
    },
    participant_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "participant",
    },
  },
  grant_application: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    project_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "project",
    },
    participant_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "participant",
    },
    organisation_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "organisation",
    },
    requested_amount: { kind: "number", nullable: false },
    grant_type: { kind: "string", nullable: false, maxLength: 30 },
    application_document_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "document",
    },
    notes: { kind: "string", nullable: true },
  },
  grant_award: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    application_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "grant_application",
    },
    amount_awarded: { kind: "number", nullable: false },
    currency: { kind: "string", nullable: false, default: "KES", maxLength: 10 },
    sector_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "business_sector",
    },
    contract_start: { kind: "string", nullable: true, date: "date" },
    contract_end: { kind: "string", nullable: true, date: "date" },
    grant_lifecycle_status: { kind: "string", nullable: false, default: "active", maxLength: 20 },
    contract_document_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "document",
    },
  },
  grant_disbursement: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    grant_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "grant_award",
    },
    amount: { kind: "number", nullable: false },
    percentage_of_total: { kind: "number", nullable: true },
    disbursement_date: { kind: "string", nullable: true, date: "date" },
    notes: { kind: "string", nullable: true },
  },
  narrative_report: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    project_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "project",
    },
    reporting_period_start: { kind: "string", nullable: false, date: "date" },
    reporting_period_end: { kind: "string", nullable: false, date: "date" },
    submitted_date: { kind: "string", nullable: true, date: "date" },
    report_status: { kind: "string", nullable: false, default: "pending", maxLength: 20 },
    notes: { kind: "string", nullable: true },
  },
  grant_report: {
    id: { kind: "number", nullable: false, integer: true, unsigned: true },
    created_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    updated_at: { kind: "string", nullable: false, default: "$now", date: "datetime" },
    status: { kind: "string", nullable: false, default: "ACTIVE", maxLength: 30 },
    status_description: { kind: "string", nullable: true, maxLength: 255 },
    is_deleted: { kind: "boolean", nullable: false, default: false },
    grant_award_id: {
      kind: "number",
      nullable: false,
      integer: true,
      unsigned: true,
      references: "grant_award",
    },
    reporting_period_start: { kind: "string", nullable: false, date: "date" },
    reporting_period_end: { kind: "string", nullable: false, date: "date" },
    due_date: { kind: "string", nullable: false, date: "date" },
    submitted_date: { kind: "string", nullable: true, date: "date" },
    document_id: {
      kind: "number",
      nullable: true,
      integer: true,
      unsigned: true,
      references: "document",
    },
    notes: { kind: "string", nullable: true },
  },
  audit_logs: {
    id: { kind: "number", nullable: false, integer: true },
    entity_type: { kind: "string", nullable: true, maxLength: 255 },
    entity_id: { kind: "number", nullable: true, integer: true },
    action: { kind: "string", nullable: false, maxLength: 50 },
    source: { kind: "string", nullable: true, values: ["HTTP", "KAFKA"] },
    performed_by: { kind: "number", nullable: true, integer: true },
    performed_at: { kind: "string", nullable: false, date: "datetime" },
    endpoint: { kind: "string", nullable: true, maxLength: 255 },
    event_name: { kind: "string", nullable: true, maxLength: 255 },
    input_payload: { kind: "string", nullable: true },
    previous_state: { kind: "string", nullable: true },
    new_state: { kind: "string", nullable: true },
  },
};
