import { z } from "zod";
import { createEnvelopeSchema, createPaginatedSchema } from "@/lib/api/contracts";
const id = z.number().int().positive();
const standard = { id, status: z.string(), is_deleted: z.boolean() };
export const userSchema = z.object({ ...standard, first_name: z.string(), middle_name: z.string().nullable(), last_name: z.string(), username: z.string(), email: z.string().nullable(), phone_number: z.string().nullable() });
export const roleSchema = z.object({ ...standard, code: z.string(), name: z.string(), description: z.string().nullable(), is_system_role: z.boolean() });
export const permissionSchema = z.object({ ...standard, code: z.string(), module: z.string(), name: z.string(), description: z.string().nullable() });
export const userRoleSchema = z.object({ ...standard, user_id: id, role_id: id, pillar_id: id.nullable() });
export const rolePermissionSchema = z.object({ ...standard, role_id: id, permission_id: id });
export const pillarSchema = z.object({ id, name: z.string(), code: z.string() });
export const pillarCatalogSchema = createEnvelopeSchema(z.array(pillarSchema).nullable());
export const userListSchema = createEnvelopeSchema(createPaginatedSchema(userSchema).nullable());
export const roleListSchema = createEnvelopeSchema(createPaginatedSchema(roleSchema).nullable());
export const permissionListSchema = createEnvelopeSchema(createPaginatedSchema(permissionSchema).nullable());
export const userRoleListSchema = createEnvelopeSchema(createPaginatedSchema(userRoleSchema).nullable());
export const rolePermissionListSchema = createEnvelopeSchema(createPaginatedSchema(rolePermissionSchema).nullable());
export const userMutationSchema = createEnvelopeSchema(userSchema.nullable());
export const roleMutationSchema = createEnvelopeSchema(roleSchema.nullable());
export const permissionMutationSchema = createEnvelopeSchema(permissionSchema.nullable());
export const userRoleMutationSchema = createEnvelopeSchema(userRoleSchema.nullable());
export const rolePermissionMutationSchema = createEnvelopeSchema(rolePermissionSchema.nullable());
export const userInputSchema = z.object({ firstName: z.string().trim().min(1).max(80), lastName: z.string().trim().min(1).max(80), username: z.string().trim().min(3).max(60).regex(/^[a-zA-Z0-9._-]+$/), email: z.email().max(160).optional(), phoneNumber: z.string().trim().max(12).optional() });
export const userUpdateSchema = z.object({ id, firstName: z.string().trim().min(1).max(80), lastName: z.string().trim().min(1).max(80), email: z.email().max(160).nullable().optional(), phoneNumber: z.string().trim().max(12).nullable().optional(), status: z.enum(["ACTIVE", "DISABLED", "INACTIVE"]).optional() });
export const roleInputSchema = z.object({ code: z.string().trim().min(2).max(40).regex(/^[A-Z][A-Z0-9_]+$/), name: z.string().trim().min(2).max(120), description: z.string().trim().max(500).optional() });
export const roleUpdateSchema = z.object({ id, name: z.string().trim().min(2).max(120), description: z.string().trim().max(500).nullable().optional() });
export const permissionInputSchema = z.object({ code: z.string().trim().min(2).max(60).regex(/^[A-Z][A-Z0-9_]+$/), module: z.string().trim().min(2).max(40).regex(/^[A-Z][A-Z0-9_]+$/), name: z.string().trim().min(2).max(160), description: z.string().trim().max(500).optional() });
export const userRoleInputSchema = z.object({ userId: id, roleId: id, pillarId: id.nullable(), enabled: z.boolean() });
export const rolePermissionInputSchema = z.object({ roleId: id, permissionId: id, enabled: z.boolean() });
